[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.6.0"
solana-alt-bn128-bls = { path = "../../solana-alt-bn128-bls" }
solana-program = "1.17.14"

[dev-dependencies]
mollusk-svm = "0.0.11"
solana-sdk = "2.0.1"
